baseURL = '/'
languageCode = 'vi-vietnam'
title = 'Miền Tây Nhớ'
theme = 'ananke'
defaultContentLanguage = "vi"
[languages]
  [languages.vi]
    languageCode = 'vi-vietnam'
    languageDirection = 'ltr'
    languageName = 'vietnames'
    weight = 1
[params]
    name = 'Phúc Ú'
    link = 'https://google.com'
    custom_css = ['css/custom.css']
    date_format = '02/01/2006'

[menu]
    [[menu.main]]
        name = 'Trang chủ'
        url = '/'
        weight = 1
    [[menu.main]]
        name = 'Món ăn miền tây'
        url = '/chuyen-muc/mon-an-mien-tay'
        weight = 2
[permalinks]
    [permalinks.page]
        posts = '/:slug/'

[taxonomies]
    category = "chuyen-muc"
