baseURL = 'https://namkyxua.com/'
languageCode = 'vi-vietnam'
title = 'Nam Kỳ Xưa'
theme = 'pehtheme-hugo-main'
defaultContentLanguage = "vi"
removePathAccents = true
paginate = 6
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.vi]
    languageCode = 'vi-vietnam'
    languageDirection = 'ltr'
    languageName = 'vietnames'
    weight = 1
[pagination]
    pagerSize = 6
[params]
    selfHosted = true
    mainSections = ["mon-ngon-mien-tay",'nhan-vat-noi-tieng-mien-nam','cuoc-song']
    description = 'Khám phá Sài Gòn xưa, ẩm thực miền Nam, văn hóa và phong tục miền Tây tại NamKyXua.com – nơi lưu giữ ký ức Nam Kỳ xưa sống động.'
    dateFormat = "02 January 2006"
    comments = true
    facebook = 'phucsg.lhp'
    instagram = 'lphuc88'
    x = 'p__lux'
    logos = '/images/logo.png'

[related]
  includeNewer = true
  threshold = 20
  toLower = true

  [[related.indices]]
    name = "categories"
    weight = 80

  [[related.indices]]
    name = "keywords"
    weight = 50

  [[related.indices]]
    name = "date"
    weight = 10

[params.author]
    name = 'Phúc Mập'
    email = 'Lhp0988@gmail.com'
    phone = '0567377979'
    avatar = '/images/avatar.webp'
    bio = 'Là một người con của Miền Tây sông nước với mong muốn tạo ra một nơi hoài niệm về Nam kỳ xưa và Miền Tây. Nếu mọi người muốn đóng góp thì có thể gửi mail về cho mình về những bài viết những điểm du lịch đẹp ở miền Nam và miền Tây'
[services.disqus]
    shortname = 'mientayblog'

[services]
  [services.googleAnalytics]
    id = 'G-BBNTN7HEBR'   
[permalinks]
    mon-ngon-mien-tay = '/mon-ngon-mien-tay/:slug/'
    nhan-vat-noi-tieng-mien-nam = '/nhan-vat-noi-tieng-mien-nam/:slug/'
    cuoc-song = '/cuoc-song-nguoi-nam-ky/:slug'
    tag = '/tags/:slug/'
[menus]
    [[menus.main]]
        name = 'Trang chủ'
        url = '/'
        weight = 1
[taxonomies]
    category = 'categories'
    tag = 'tags'

    


