baseURL = '/'
languageCode = 'vi-vietnam'
title = 'Miền Tây Nhớ'
theme = 'ananke'
defaultContentLanguage = "vi"
[languages]
  [languages.vi]
    languageCode = 'vi-vietnam'
    languageDirection = 'ltr'
    languageName = 'vietnames'
    weight = 1
[params]
    name = 'Phúc Ú'
    link = 'https://google.com'
    custom_css = ['css/custom.css']
    date_format = '02/01/2006'
[permalinks]
    [permalinks.page]
        mon-tan-mien-tay = '/mon-an-mien-tay/:slug/'
    [permalinks.section]
        mon-an-mien-tay = '/mon-an-mien-tay/'
[menus]
    [[menus.main]]
        name = 'Trang chủ'
        url = '/'
        weight = 1
    


