baseURL = '/'
languageCode = 'vi-vietnam'
title = 'Nam Kỳ Xưa'
theme = 'mainroad'
defaultContentLanguage = "vi"

[pagination]
    pagerSize = 8
[services]
  [services.disqus]
    shortname = 'mientayblog'
[languages]
  [languages.vi]
    languageCode = 'vi-vietnam'
    languageDirection = 'ltr'
    languageName = 'vietnames'
    weight = 1
[params]
    name = 'Phúc Ú'
    link = 'https://google.com'
    date_format = '02/01/2006'
    mainSections = ['mon-an-mien-tay','nhan-vat']
    readmore = true
    customCss = ['css/custom.css']
    authorbox = true
[params.author]
    name = 'Phúc Mập'
    email = 'Lhp0988@gmail.com'
    phone = '0567377979'
    avatar = '/images/avatar.webp'
    description = 'Là một người con của Miền Tây sông nước với mong muốn tạo ra một nơi hoài niệm về Nam kỳ xưa và Miền Tây. Nếu mọi người muốn đóng góp thì có thể gửi mail về cho mình về những bài viết những điểm du lịch đẹp ở miền Nam và miền Tây'
[params.thumbnail]
    visibility = ['list']
[params.sidebar]
    home = 'right'
    list = 'right'
    single = 'right'
    widgets = ['social','categories','taglist']
[params.widgets.social]
    facebook = 'phucsg.lhp'
[permalinks]
    [permalinks.page]
        mon-tan-mien-tay = '/mon-an-mien-tay/:slug/'
        NhanVat = '/nhan-vat/:slug/'
    [permalinks.section]
        mon-an-mien-tay = '/mon-an-mien-tay/'
        nhan-vat = '/nhan-vat/'
[menus]
    [[menus.main]]
        name = 'Trang chủ'
        url = '/'
        weight = 1
[taxonomy]
    category = 'categories'
    tag = 'tags'

    


