baseURL = '/'
languageCode = 'vi-vietnam'
title = 'Miền Tây Nhớ'
theme = 'mainroad'
defaultContentLanguage = "vi"
[languages]
  [languages.vi]
    languageCode = 'vi-vietnam'
    languageDirection = 'ltr'
    languageName = 'vietnames'
    weight = 1
[params]
    name = 'Phúc Ú'
    link = 'https://google.com'
    date_format = '02/01/2006'
    mainSections = ['mon-an-mien-tay','nhan-vat']
    readmore = true
    customCss = ['css/custom.css']
[params.thumbnail]
    visibility = ['list']
[params.sidebar]
    home = 'right'
    list = 'right'
    single = 'right'
    widgets = ['search','social']
[permalinks]
    [permalinks.page]
        mon-tan-mien-tay = '/mon-an-mien-tay/:slug/'
        NhanVat = '/nhan-vat/:slug/'
    [permalinks.section]
        mon-an-mien-tay = '/mon-an-mien-tay/'
        nhan-vat = '/nhan-vat/'
[menus]
    [[menus.main]]
        name = 'Trang chủ'
        url = '/'
        weight = 1
    


