backend:
  name: git-gateway
  branch: main   # đổi thành nhánh bạn đang dùng
media_folder: "static/uploads"     # nơi lưu hình
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Ngày", name: "date", widget: "datetime"}
      - {label: "Nội dung", name: "body", widget: "markdown"}
      - {label: "Ảnh đại diện", name: "thumbnail", widget: "image"}
