backend:
  name: github
  repo: username/hugoblog # Thay bằng repo của bạn
  branch: main
  base_url: callback.lhp0988.workers.dev # URL của Cloudflare Worker xử lý OAuth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Bài viết"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Mô tả", name: "description", widget: "text" }
      - { 
          label: "Chuyên mục", 
          name: "categories", 
          widget: "list", 
          default: ["tin-tuc"] 
        }
      - { label: "Nội dung", name: "body", widget: "markdown" }