backend:
  name: github
  repo: phuclesg/hugoblog # Thay bằng repo của bạn
  branch: main
  base_url: https://callback.lhp0988.workers.dev # URL của Cloudflare Worker xử lý OAuth

media_folder: "static/images"
public_folder: "/images"

collections:
  # Collection cho Món Ngon
  - name: "mon_ngon"
    label: "Món Ngon"
    folder: "content/mon-ngon"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { 
          label: "Chuyên mục", 
          name: "categories", 
          widget: "list", 
          default: ["mon-ngon"] 
        }
      - { label: "Ảnh minh họa", name: "image", widget: "image", required: false }
      - { label: "Nội dung", name: "body", widget: "markdown" }

  # Collection cho Nhân Vật
  - name: "nhan_vat"
    label: "Nhân Vật"
    folder: "content/nhan-vat"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tên nhân vật", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { 
          label: "Chuyên mục", 
          name: "categories", 
          widget: "list", 
          default: ["nhan-vat"] 
        }
      - { label: "Tiểu sử tóm tắt", name: "description", widget: "text" }
      - { label: "Nội dung chi tiết", name: "body", widget: "markdown" }
      
# Collection cho đời sống
  - name: "doi_song"
    label: "Đời sống"
    folder: "content/doi-song"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tên nhân vật", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { 
          label: "Chuyên mục", 
          name: "categories", 
          widget: "list", 
          default: ["nhan-vat"] 
        }
      - { label: "Tiểu sử tóm tắt", name: "description", widget: "text" }
      - { label: "Nội dung chi tiết", name: "body", widget: "markdown" }
      